# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    csrf_protection: true
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_lifetime: 0
        gc_maxlifetime: 3600

    #esi: true
    #fragments: true

    form:
        csrf_protection:
            enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
